### ISSUE TITLE
Config isn't constant.

### ISSUE THREAD

**Issue by Lizardsaregay** [JustAlittleWolf/EasyNavigator#1]
Config is being reset on every game restart, discarding all the changes made.

**Comment by JustAlittleWolf** [comment]
Which version of Yet-Another-Config-Lib are you using?

**Comment by theprodigy2013** [comment]
The newest one, 3.2.1

**Comment by JustAlittleWolf** [comment]
Thanks for creating the issue!
It has been fixed in 1.0.5
