### ISSUE TITLE
[Feature Request] Immersive update 

### ISSUE THREAD

**Issue by zeid0ne** [JustAlittleWolf/EasyNavigator#2]
Hi, 

First thanks for the mod, it's a good idea.

I have a feature request for an "immersive update".

First, add a config option to toggle or not the immersive mode.

If immersive is enabled there is two change :

- clicking on a coordinate in chat without a compass in inventory doesnt work and show a message like "Having a compass in my inventory could be usefull to know my way onto these coordonates". Same with the command.

- crouching and left clicking a compass show a gui that ask for coordinates, then do your mod stuff about these coordinates. Maybe that could be enabled even if immersive mode is not enabled.

Thanks again for considering this, and i understand if you will not do it.

**Comment by JustAlittleWolf** [comment]
Hmm this seems like a good idea, however I see a few minor issues with your second point. What would be easy to implement, and also fairly easy to understand as a user is to have the HUD-Compass from the mod only show when you have a compass in your inventory.
Also I am not sure if I fully understand your first point, would you want the compass that's in your inventory to then point to the coordinates or have it work like I described above? Modifying the compass client side only might bring up some issues with server syncing and TBH I really want this mod to stay client-only.

The GUI is also a good Idea, however I it would take me a while to figure out custom GUIS, the command works just as well / is probably also faster to use in my opinion, as you still have to type out your coordinates in both cases.

**Comment by zeid0ne** [comment]
"What would be easy to implement, and also fairly easy to understand as a user is to have the HUD-Compass from the mod only show when you have a compass in your inventory." => this would be perfect !

After thinking about it again, i agree with you, / are faster than GUI, and GUI is harder to do and maintain,, and not very more immersive than /.

**Comment by JustAlittleWolf** [comment]
Hey, the feature your requested should be there in the newest version 1.1.0. Thanks for the great suggestion!
