### ISSUE TITLE
[Enhancement] Config option to suppress chat output

### ISSUE THREAD

**Issue by tadm12** [JustAlittleWolf/EasyNavigator#3]
A config option to surpress or customize the message sent to chat when using the `/navigate` or `/navigation` commands would be appreciated 🙂

**Comment by JustAlittleWolf** [comment]
Thanks for the suggestion, I think it is a great idea! For now I have implemented a toggle in the settings, so you can disable all messages from the mod. I don't have a lot of time at the moment but maybe I'll come back later with a more refined selection of settings so you can specifically toggle messages.
