### ISSUE TITLE
Incompatibility with CalcMod

### ISSUE THREAD

**Issue by UltimatChamp** [JustAlittleWolf/EasyNavigator#5]
**CalcMod:** https://modrinth.com/mod/calcmod
![image](https://github.com/JustAlittleWolf/EasyNavigator/assets/140878474/0ad09c9a-4fbf-451d-861d-d25fce728f9b)

**Comment by JustAlittleWolf** [comment]
I think this is only visual, and the coordinates still route the player to the correct position. I will get to fixing this though.
