### ISSUE TITLE
Unexpected Co-ords in Screenshots

### ISSUE THREAD

**Issue by UltimatChamp** [JustAlittleWolf/EasyNavigator#6]
![image](https://github.com/JustAlittleWolf/EasyNavigator/assets/140878474/89f55e60-973f-49d5-8810-83e99a4217a3)

**Comment by UltimatChamp** [comment]
_(btw thanks for the fix in 1.2.0 | I just noticed this issue😅)_

**Comment by JustAlittleWolf** [comment]
Well thanks for reporting the issues! It helps the user experience a lot when there are no little bugs like this.
